YunWonYong/Programmers

Algorithms/src/nattybear/level1/RecommendNewId.java
README.md

Add RecommendNewId.java after reverting previous commit

Add RecommendNewId.java

---

README.md

pu134340 branch add

---

Algorithms/src/andy/javascript/level1/KstNumber.js
Algorithms/src/andy/level1/KstNumber.java

프로그래머스 레벨1 , K번째수
세문제중에서 가장 쉬워보이는 첫번째 문제

Programmers Level 1 , K번째수

---

Algorithms/src/andy/javascript/level1/UnfinishedPlayer.js
Algorithms/src/andy/level1/UnfinishedPlayer.java

프로그래머스 Level 1, 완주하지 못한 선수

---

Algorithms/src/ywy/java/level1/MakePrimeNumber.java
Algorithms/src/ywy/java/level1/UnfinishedPlayer.java
Algorithms/src/ywy/java/level1/test/MakePrimeNumberTest.java
Algorithms/src/ywy/java/level1/test/UnfinishedPlayerTest.java
Algorithms/src/ywy/javascript/level1/KthPlayer.js
Algorithms/src/ywy/javascript/level1/MakePrimeNumber.js
Algorithms/src/ywy/javascript/level1/UnfinishedPlayer.js

2021-11-04 #52 clear

---

Algorithms/src/andy/javascript/level1/MakePrimeNumber.js
Algorithms/src/andy/level1/MakePrimeNumber.java

프로그래머스 Level 1, 소수만들기

---

Algorithms/src/ywy/java/level1/MakePrimeNumber.java
Algorithms/src/ywy/java/level1/test/MakePrimeNumberTest.java

2021-11-06 소수구하기 리팩토링

---

Algorithms/src/ywy/java/level1/Pokemon.java
Algorithms/src/ywy/java/level1/PokemonSet.java
Algorithms/src/ywy/javascript/level1/Pokemon.js

<div>
<span>
</span>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<span>   
</span>
<br>
<span>
HashSet을 사용하지 않은 성능
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
HashSet을 사용한 성능
</span>
</div>   
<h1>가야할 길이 너무 머네요 ㅠㅠ</h1>
배열을 카피할 때 시간과 공간을 잡아 먹는거 같은데 ㄷㄷ 잘 모르겠네요.....

2021-11-07 #67 clear

---

Algorithms/src/andy/javascript/level1/MockTest.js
Algorithms/src/andy/javascript/level1/SportsUniform.js
Algorithms/src/andy/level1/MockTest.java
Algorithms/src/andy/level1/SportsUniform.java

그냥 평범하게 풀었습니다. 어차피 다 채점해야 되기때문에 반복문으로 채점했어요.^^

프로그래머스 Level 1,모의고사

---

Algorithms/src/ywy/java/Main.java
Algorithms/src/ywy/java/level1/MockExam.java
Algorithms/src/ywy/java/level1/test/MockExamTest.java
Algorithms/src/ywy/javascript/level1/MockExam.js

캬캬캬 풀긴 풀었는데 진짜... 진지하게 한글 공부 해야 하나 생각했습니다. ㅋㅋ

2021-11-10 #65 clear

---

Algorithms/src/ywy/java/level1/GymSuit.java
Algorithms/src/ywy/java/level1/test/GymSuitTest.java
Algorithms/src/ywy/java/level1/test/InnerProductTest.java
Algorithms/src/ywy/java/level1/test/MakePrimeNumberTest.java
Algorithms/src/ywy/java/level1/test/NegativeAndPositiveNumbersPlusTest.java
Algorithms/src/ywy/java/level1/test/UnfinishedPlayerTest.java
Algorithms/src/ywy/javascript/level1/GymSuit.js

오늘 스터디 너무 만족스럽습니다!! ㅎㅎ
제가 너무 많이 배워가서 약간..? 이기적이지만 감사합니다 ㅎㅎ;;
저도 많이 공부해서 기회가되면 알려드리고 싶습니다 ㅠㅠ
closed #66

2021-11-13 #66 clear

---

Algorithms/src/ywy/java/level1/DivisorCountPlus.java
Algorithms/src/ywy/java/level1/test/DiviserCountPlusTest.java
Algorithms/src/ywy/javascript/level1/DivisorCountPlus.js

2021-11-14 #76 clear

---

Algorithms/src/andy/javascript/level1/SubmultiplePlusMinus.js
Algorithms/src/andy/level1/SubmultiplePlusMinus.java

프로그래머스 Level 1,약수의 개수와 덧셈

---

Algorithms/src/ywy/java/level1/TernaryFlip.java
Algorithms/src/ywy/java/level1/test/TernaryFlipTest.java
Algorithms/src/ywy/javascript/level1/TernaryFlip.js

- #77 
21시에 잘려고 눈감았는데 갑자기 준규님이 가르쳐주신 방법이 떠올라서 
코딩해봤는데 통과 했네요.  ㅋㅋㅋ  
감사합니다 준규님 ㅋㅋㅋㅋ

2021-11-17 #77 clear

---

Algorithms/src/andy/javascript/level1/TernaryNotation.js
Algorithms/src/andy/level1/TernaryNotation.java

2021-11-19 #77 프로그래머스 Level 1,3진법 뒤집기

프로그래머스 Level 1,3진법 뒤집기

---

Algorithms/src/ywy/java/level1/Budget.java
Algorithms/src/ywy/java/level1/test/BudgetTest.java
Algorithms/src/ywy/javascript/level1/Budget.js

ㅎㅎ 꿀잼 
제가 코딩하는 버블정렬은 버블정렬인가!? ㅋㅋㅋ

2021-11-21 #86 clear

---

Algorithms/src/andy/javascript/level1/budget.js
Algorithms/src/andy/javascript/level1/twopickplus.js
Algorithms/src/andy/javascript/level1/year2016.js
Algorithms/src/andy/level1/twopickplus.java
Algorithms/src/andy/level1/year2016.java
Algorithms/src/budget/budget.java

2021-11-22 #86 clear, #87 clear, #88 clear
프로그래머스 Level 1, 2016년
프로그래머스 Level 1, 예산
프로그래머스 Level 1, 두 개 뽑아서 더하기

2021-11-22 #86 clear, #87 clear, #88 clear

---

Algorithms/src/ywy/java/level1/TwoNumberPlus.java
Algorithms/src/ywy/java/level1/Year2016.java
Algorithms/src/ywy/java/level1/test/TwoNumberPlusTest.java
Algorithms/src/ywy/java/level1/test/year2016Test.java
Algorithms/src/ywy/javascript/level1/TwoNumberPlus.js
Algorithms/src/ywy/javascript/level1/Year2016.js

코테를 준비하며 binary search와 insert sort를 사용해 보았습니다 ㅎㅎ;;;
binary search를 응용하다 머리 뿌셔지는줄.. 알았는데 급 궁금하게 생기네요 ㅎㅎ;;
insert sort는 O(n2)고 binary search는 O(log N)인데 insert sort와 binary search를 같이 사용하면 
insert sort할 때 삽입할 요소를 탐색하는 것이 n2 중 n을 차지하니까 binary search를 사용하니 log N + N 은 O(n) 성능으로 insert sort를 쓸 수 있을까요 ?;;;
아.. 따로 올렸어야 했는데 ㅠㅠ  
enum은 좋은 놈이다 ㅋㅋ

2021-11-23 #87, #88 clear

---

Algorithms/src/ywy/java/level1/InsufficientAmount.java
Algorithms/src/ywy/java/level1/test/InsufficientAmountTest.java
Algorithms/src/ywy/javascript/level1/InsufficientAmount.js

2021-11-27 #95 Clear

---

Algorithms/src/ywy/java/level1/SecretMap.java
Algorithms/src/ywy/java/level1/test/FirstWeekOfDecember.java
Algorithms/src/ywy/java/level1/test/SecretMapTest.java
Algorithms/src/ywy/javascript/level1/SecretMap.js

2021-12-05 #101 Clear

---

Algorithms/src/ywy/java/level1/GetMiddleLetter.java
Algorithms/src/ywy/java/level1/test/GetMiddleLetterTest.java
Algorithms/src/ywy/javascript/level1/GetMiddleLetter.js

2021-12-05 #102 clear

---

Algorithms/src/ywy/java/level1/DartsGame.java
Algorithms/src/ywy/java/level1/test/DartsGameTest.java
Algorithms/src/ywy/javascript/level1/DartsGame.js

2021-12-05 #103 clear

---

Algorithms/src/andy/javascript/level1/DartGame.js
Algorithms/src/andy/javascript/level1/GetMiddleLetter.js
Algorithms/src/andy/javascript/level1/SecretMap.js
Algorithms/src/andy/level1/DartGame.java
Algorithms/src/andy/level1/GetMiddleLetter.java
Algorithms/src/andy/level1/SecretMap.java

프로그래머스 Level 1,[1차] 비밀지도
프로그래머스 Level 1,가운데 글자 가져오기
프로그래머스 Level 1,[1차] 다트 게임

Clear #101 #102 #103

---

Algorithms/src/ljh/level1/java/DartsGame.java
Algorithms/src/ljh/level1/js/DartsGame.js

안녕하세요. 정희 입니다.
미숙한 부분이 많지만 열심히 참여해서 많이 배우겠습니다.
잘 부탁드립니다.

2021-12-12 init ljh

---

Algorithms/src/ywy/java/level1/DivisibleNumber.java
Algorithms/src/ywy/java/level1/test/cases/DivisibleNumberTest.java
Algorithms/src/ywy/javascript/level1/DivisibleNumber.js

2021-12-14 ywy #110 clear

---

.github/ISSUE_TEMPLATE/------------.md

운 좋게 알게 됐지만 바로 사용하려면 프로젝트 카드들을 삭제해야 함... ㅠㅠ

Update issue templates

---

Algorithms/src/ywy/java/level1/HateSameNumber.java
Algorithms/src/ywy/java/level1/test/DecemberWeekOf2.java
Algorithms/src/ywy/java/level1/test/cases/HateSameNumberTest.java
Algorithms/src/ywy/javascript/level1/HateSameNumber.js

2021-12-14 ywy #109 clear

---

Algorithms/src/ywy/java/level1/SumBetweenTwoNumbers.java
Algorithms/src/ywy/java/level1/test/cases/SumBetweenTwoNumbersTest.java
Algorithms/src/ywy/javascript/level1/SumBetweenTwoNumbers.js

2021-12-14 ywy #111 clear

---

Ywy/JAVA/src/level1/MyWaySorting.java
Ywy/JAVA/src/level1/PAndYCount.java
Ywy/JAVA/src/level1/StringDescending.java
Ywy/JAVA/src/level1/test/AllTests.java
Ywy/JAVA/src/level1/test/DecemberWeekOf3.java
Ywy/JAVA/src/level1/test/cases/MyWaySortingTest.java
Ywy/JAVA/src/level1/test/cases/PAndYCountTest.java
Ywy/JAVA/src/level1/test/cases/StringDescendingTest.java
Ywy/JavaScript/level1/MyWaySorting.js
Ywy/JavaScript/level1/PAndYCount.js
Ywy/JavaScript/level1/StringDescending.js
Ywy/JavaScript/level1/test/MyWaySorting.test.js
Ywy/JavaScript/level1/test/PAndYCount.test.js
Ywy/JavaScript/level1/test/StringDescending.test.js

1. 문자열 내 마음대로 정렬하기
2. 문자열 내 p와 y의 개수
3. 문자열 내림차순으로 배치하기

2021-12-21 ywy add java, js

---

nattybear/level1/.gitignore
nattybear/level1/문자열-내-p와-y의-개수/Solution.java
nattybear/level1/문자열-내-p와-y의-개수/solution.js
nattybear/level1/문자열-내-마음대로-정렬하기/Solution.java
nattybear/level1/문자열-내-마음대로-정렬하기/solution.js
nattybear/level1/문자열-내림차순으로-배치하기/Solution.java
nattybear/level1/문자열-내림차순으로-배치하기/solution.js

* [문자열 내 마음대로 정렬하기](https://programmers.co.kr/learn/courses/30/lessons/12915)
* [문자열 내 p와 y의 개수](https://programmers.co.kr/learn/courses/30/lessons/12916)
* [문자열 내림차순으로 배치하기](https://programmers.co.kr/learn/courses/30/lessons/12917)

Solve problems

---

Andy/src/level1/java/StringPYCount.java
Andy/src/level1/java/StringSortInverse.java
Andy/src/level1/java/StringSortMine.java
Andy/src/level1/javascript/StringPYCount.js
Andy/src/level1/javascript/StringSortInverse.js
Andy/src/level1/javascript/StringSortMine.js

프로그래머스 Level 1, 문자열 내 마음대로 정렬하기
프로그래머스 Level 1, 문자열 내 p와 y의 개수
프로그래머스 Level 1, 문자열 내림차순으로 배치하기

Andy : 문자열 내 마음대로 정렬하기,문자열 내 p와 y의 개수,문자열 내림차순으로 배치하기

---

Suhyun/JS/Naerim.js
Suhyun/JS/Omoikiri.js
Suhyun/JS/PtoY.js
Suhyun/Java/Naerim.java
Suhyun/Java/Omoikiri.java
Suhyun/Java/PtoY.java

Suhyun:12월 4주차

---

nattybear/level1/문자열-다루기-기본/Solution.java
nattybear/level1/문자열-다루기-기본/solution.js
nattybear/level1/서울에서-김서방-찾기/Solution.java
nattybear/level1/서울에서-김서방-찾기/solution.js
nattybear/level1/소수-찾기/Solution.java
nattybear/level1/소수-찾기/solution.js

* [문자열 다루기 기본](https://programmers.co.kr/learn/courses/30/lessons/12918)
* [서울에서 김서방 찾기](https://programmers.co.kr/learn/courses/30/lessons/12919)
* [소수 찾기](https://programmers.co.kr/learn/courses/30/lessons/12921)

Solve lessons

---

ljh/actionTest_jh.txt
ljh/java/src/level1/FindKim.java
ljh/java/src/level1/HandlingString.java
ljh/java/src/level1/SearchPrimeNumber.java
ljh/java/src/level1/test/FindKimTest.java
ljh/java/src/level1/test/HandlingStringTest.java
ljh/java/src/level1/test/SearchPrimeNumberTest.java
ljh/javascript/level1/FindKim.js
ljh/javascript/level1/HandlingString.js
ljh/javascript/level1/SearchPrimeNumber.js
ljh/javascript/level1/test/FindKim.test.js
ljh/javascript/level1/test/HandlingString.test.js
ljh/javascript/level1/test/SearchPrimeNumber.test.js

- 문자열 다루기 기본
- 서울에서 김서방 찾기
- 소수 찾기
^-^

solve problems(211224 - 211230)

---

Andy/src/level1/etc/basicString.cpp
Andy/src/level1/etc/basicString.cs
Andy/src/level1/etc/basicString.py
Andy/src/level1/etc/findPrimeNumber.cs
Andy/src/level1/etc/findPrimeNumber.py
Andy/src/level1/etc/finidPrimeNumber.cpp
Andy/src/level1/etc/seoulKim.cpp
Andy/src/level1/etc/seoulKim.cs
Andy/src/level1/etc/seoulKim.py
Andy/src/level1/java/basicString.java
Andy/src/level1/java/findPrimeNumber.java
Andy/src/level1/java/seoulKim.java
Andy/src/level1/javascript/basicString.js
Andy/src/level1/javascript/findPrimeNumber.js
Andy/src/level1/javascript/seoulKim.js

프로그래머스 Level 1,문자열 다루기 기본
프로그래머스 Level 1,소수 찾기
프로그래머스 Level 1,서울에서 김서방 찾기

2021-12-29 Andy 

---

Ywy/JAVA/src/level1/CaesarCipher.java
Ywy/JAVA/src/level1/InfinityWatermelon.java
Ywy/JAVA/src/level1/StringToIntegerChange.java
Ywy/JAVA/src/level1/test/JanuaryWeekOf1.java
Ywy/JAVA/src/level1/test/cases/CaesarCipherTest.java
Ywy/JAVA/src/level1/test/cases/InfinityWatermelonTest.java
Ywy/JAVA/src/level1/test/cases/StringToIntegerChangeTest.java
Ywy/JavaScript/level1/CaesarCipher.js
Ywy/JavaScript/level1/InfinityWatermelon.js
Ywy/JavaScript/level1/StringToIntegerChange.js
Ywy/JavaScript/level1/test/CaesarCipher.test.js
Ywy/JavaScript/level1/test/InfinityWatermelon.test.js
Ywy/JavaScript/level1/test/StringToIntegerChange.test.js

1. 수박수박수박수박수박수?
2. 문자열을 정수로 바꾸기
3. 시저 암호 (시져시져~)

2022-01-01 ywy

---

Andy/src/level1/java/caesarpassword.java
Andy/src/level1/java/stringtoint.java
Andy/src/level1/java/subak.java
Andy/src/level1/javascript/caesarpassword.js
Andy/src/level1/javascript/stringtoint.js
Andy/src/level1/javascript/subak.js

프로그래머스 Level 1,수박수박수박수박수박수?
프로그래머스 Level 1,문자열을 정수로 바꾸기
프로그래머스 Level 1,시저 암호

2022-01-05 Andy

---

ljh/java/src/level1/MakeStrangeText.java
ljh/java/src/level1/ReverseNumber.java
ljh/java/src/level1/SumOfDigit.java
ljh/java/src/level1/SumOfDivisor.java
ljh/java/src/level1/test/MakeStrangeTextTest.java
ljh/java/src/level1/test/ReverseNumberTest.java
ljh/java/src/level1/test/SumOfDigitTest.java
ljh/java/src/level1/test/SumOfDivisorTest.java
ljh/javascript/level1/MakeStrangeText.js
ljh/javascript/level1/ReverseNumber.js
ljh/javascript/level1/SumOfDigit.js
ljh/javascript/level1/SumOfDivisor.js
ljh/javascript/level1/test/MakeStrangeText.test.js
ljh/javascript/level1/test/ReverseNumber.test.js
ljh/javascript/level1/test/SumOfDigit.test.js
ljh/javascript/level1/test/SumOfDivisor.test.js

220108 - 220114
-------------------
- [약수의 합](https://programmers.co.kr/learn/courses/30/lessons/12928)
- [이상한 문자 만들기](https://programmers.co.kr/learn/courses/30/lessons/12930)
- [자릿수 더하기](https://programmers.co.kr/learn/courses/30/lessons/12931)
- [자연수 뒤집어 배열로 만들기](https://programmers.co.kr/learn/courses/30/lessons/12932)

solve problems _ljh

---

ljh/java/src/level1/ArrangeIntegerInDescendingOrder.java
ljh/java/src/level1/EvenAndOdd.java
ljh/java/src/level1/IsIntegerSquareRoot.java
ljh/java/src/level1/RemoveSmallestNumber.java
ljh/java/src/level1/test/ArrangeIntegerInDescendingOrderTest.java
ljh/java/src/level1/test/EvenAndOddTest.java
ljh/java/src/level1/test/IsIntegerSquareRootTest.java
ljh/java/src/level1/test/RemoveSmallestNumberTest.java
ljh/javascript/level1/ArrangeIntegerInDescendingOrder.js
ljh/javascript/level1/EvenAndOdd.js
ljh/javascript/level1/IsIntegerSquareRoot.js
ljh/javascript/level1/RemoveSmallestNumber.js
ljh/javascript/level1/test/ArrangeIntegerInDescendingOrder.test.js
ljh/javascript/level1/test/EvenAndOdd.test.js
ljh/javascript/level1/test/IsIntegerSquareRoot.test.js
ljh/javascript/level1/test/RemoveSmallestNumber.test.js

- [정수 내림차순으로 배치하기](https://programmers.co.kr/learn/courses/30/lessons/12933)
- [정수 제곱근 판별](https://programmers.co.kr/learn/courses/30/lessons/12934)
- [제일 작은 수 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12935)
- [짝수와 홀수](https://programmers.co.kr/learn/courses/30/lessons/12937)

solve problems_ljh 

---

ljh/java/src/level1/MatrixAddition.java
ljh/java/src/level1/PhoneNumberMasking.java
ljh/java/src/level1/PrintRectangleStar.java
ljh/java/src/level1/Report.java
ljh/java/src/level1/Report2.java
ljh/java/src/level1/XMultiple.java
ljh/javascript/level1/MatrixAddition.js
ljh/javascript/level1/PhoneNumberMasking.js
ljh/javascript/level1/PrintRectangleStar.js
ljh/javascript/level1/XMultiple.js

220129 - 220224
- [핸드폰 번호 가리기](https://programmers.co.kr/learn/courses/30/lessons/12948)
- [행렬의 덧셈](https://programmers.co.kr/learn/courses/30/lessons/12950)
- [x만큼 간격이 있는 n개의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12954)
- [직사각형 별찍기](https://programmers.co.kr/learn/courses/30/lessons/12969)
- [신고 결과 받기](https://programmers.co.kr/learn/courses/30/lessons/92334)

solve problems_ljh

---

Ywy/JAVA/src/level1/DartsGame.java
Ywy/JAVA/src/level1/RectangleStar.java
Ywy/JAVA/src/level1/ReportResult.java
Ywy/JAVA/src/level1/test/AllTests.java
Ywy/JAVA/src/level1/test/FebruaryWeekOf2.java
Ywy/JAVA/src/level1/test/cases/ReportResultTest.java
Ywy/JAVA/src/level2/OpenChatRoom.java
Ywy/JAVA/src/level2/StringCompression.java
Ywy/JAVA/src/level2/test/AllTests.java
Ywy/JAVA/src/level2/test/FebruaryWeekOf2.java
Ywy/JAVA/src/level2/test/cases/OpenChatRoomTest.java
Ywy/JAVA/src/level2/test/cases/StringCompressionTest.java
Ywy/JavaScript/level1/ReportResult.js
Ywy/JavaScript/level1/test/ReportResult.test.js
Ywy/JavaScript/level2/OpenChatRoom.js
Ywy/JavaScript/level2/StringCompression.js
Ywy/JavaScript/level2/test/OpenChatRoom.test.js
Ywy/JavaScript/level2/test/StringCompression.test.js

2022-02-07 ywy

---

nattybear/level1/로또의-최고-순위와-최저-순위/Solution.java
nattybear/level1/로또의-최고-순위와-최저-순위/solution.js

Solve lotto for the Crown

---

Ywy/JAVA/src/level2/IntactSquare.java
Ywy/JAVA/src/level2/Nara1234.java
Ywy/JAVA/src/level2/test/FebruaryWeekOf3.java
Ywy/JAVA/src/level2/test/cases/IntactSquareTest.java
Ywy/JAVA/src/level2/test/cases/Nara1234Test.java
Ywy/JavaScript/level2/IntactSquare.js
Ywy/JavaScript/level2/Nara1234.js
Ywy/JavaScript/level2/test/IntactSquare.test.js
Ywy/JavaScript/level2/test/Nara1234.test.js

**1. 1234 나라의 숫자**
**2. 멀쩡한 사각형**
어... 어렵다...
1234 나라의 숫자는 혼자 풀었는데 멀쩡한 사각형은 이틀 동안 했는데도 모르겠어서 구글링 했습니다. ㅠㅠ;;

2022-02-13 ywy

---

ljh/level2/124 나라의 숫자/Solution.java
ljh/level2/124 나라의 숫자/Solution.js
ljh/level2/멀쩡한 사각형/Solution.java
ljh/level2/멀쩡한 사각형/Solution.js

-[멀쩡한 사각형](https://programmers.co.kr/learn/courses/30/lessons/62048)
-[124 나라의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12899?language=java)

220218 ljh

---

ljh/level2/기능 개발/Develop.java
ljh/level2/기능 개발/Develop.js
ljh/level2/기능 개발/DevelopQue.java
ljh/level2/타겟 넘버/TargetNumber.java
ljh/level2/타겟 넘버/TargetNumber.js

-[기능 개발](https://programmers.co.kr/learn/courses/30/lessons/42586)
-[타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165)
혼자 나름의 방법대로 풀어보고,
문제 카테고리인 스택/큐, dfs/bfs 를 적용했습니다.
기본기가 부족하다 보니 dfs, bfs는 이해하기 힘들었네요. 
dfs를 활용한 다른 사람의 풀이들을 보고 따라 치며 공부했습니다. 타겟 넘버 javascript는 다른 사람의 문제 풀이 입니다.

2202-02-21 ljh

---

Ywy/Go/level2/기능개발/functionDevelopment.go
Ywy/Go/level2/기능개발/functionDevelopment_test.go
Ywy/Go/level2/타겟넘버/targetNumber.go
Ywy/Go/level2/타겟넘버/targetNumber_test.go
Ywy/JAVA/src/level2/TargetNumber.java
Ywy/JAVA/src/level2/test/FebruaryWeekOf4.java
Ywy/JAVA/src/level2/test/cases/TargetNumberTest.java
Ywy/JavaScript/level2/FunctionDevelopment.js
Ywy/JavaScript/level2/IntactSquare.js
Ywy/JavaScript/level2/TargetNumber.js
Ywy/JavaScript/level2/test/FuntionDevelopment.test.js
Ywy/JavaScript/level2/test/IntactSquare.test.js
Ywy/JavaScript/level2/test/TargetNumber.test.js

- 이건 왠지 쉬웠다.
- 문제가 명확하다.
- 문제를 읽고 생각한 대로 코딩했더니 한방에 통과
- 타겟넘버 문제를 수요일까지 풀어보고 시간이 남으면 리팩토링 예정
- 타겟넘버 핵 어려워서 시간 다 써버림.. ㅂㄷㅂㄷ
-----
- 답...답이없다.
- 문제를 읽어도 모르겠다...
- 입출예는 전부 통과이지만 테스트는 전부 실패다...
- 수요일까지 해보고 못 하면 검색할 예정
- **결국 검색 + 복붙... 그래프부터 공부해야겠다....ㅠ**
**준규님 pr 보고 따라하기 ㅎㅎ**

2022-02-21 ywy

---

Ywy/JAVA/src/level2/PairRemove.java
Ywy/JAVA/src/level2/RotateMatrixBorder.java
Ywy/JAVA/src/level2/test/MarchWeekOf1.java
Ywy/JAVA/src/level2/test/cases/PairRemoveTest.java
Ywy/JAVA/src/level2/test/cases/RotateMatrixBorderTest.java
Ywy/JavaScript/level2/PairRemove.js
Ywy/JavaScript/level2/RotateMatrixBorder.js
Ywy/JavaScript/level2/test/PairRemove.test.js
Ywy/JavaScript/level2/test/RotateMatrixBorder.test.js

* 이 문제는 너무 쉬웠다.
* 다음 문제가 두려워 진다...
* 처음에 O(n)으로 풀면 통과 못 하는지 알고 고민하다 일단 O(n)으로 풀어보자 해서 풀었더니 통과해버렸다...
* stack에 요소를 넣기 전에 항상 top - 1 요소와  현재 반복문의 index번째인 문자와 비교한 후 같으면 stack에서 pop하고 아니면 push
* 자바를 풀고 자바스크립트로 풀었는데 똑같은 원리로 만들었지만 효율성 2번을 통과하지 못했다. 이것 저것 만지다가 공백 한 개 더 넣었을 뿐인데 통과했다. 똑같은 코드라도 책점하는 시점에 따라 통과 여부가 결정되나?
* 제목부터 어렵다...
* 처음과 마지막 행만 모든 열의 값을 만들었었는데 제출했더니 2번만 맞음...
* 입력 받은 행과 열의 모든 원소를 채웠더니 통과했음...
* 처음엔 int라서 통과 못 하는지 알고 long으로 케스팅했는데 코드를 정리 안 했음 ㅋㅋ
* js는 막 해불자~~~ ㅋㅋ

2022-02-26 ywy

---

ljh/level2/짝지어 제거하기/DeletePair.java
ljh/level2/짝지어 제거하기/DeletePair.js
ljh/level2/행렬 테두리 회전하기/MatrixRotate.java
ljh/level2/행렬 테두리 회전하기/MatrixRotate.js

-[짝지어 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12973)
-[행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485?language=javascript)
유난히 삽질이 많았던 문제 풀이 였습니다.
행렬 테두리 회전하기에서 똑같은 코드가 반복되는 걸 보완하고 싶었는데, 쉽지가 않았어요.
조건식을 추가해서 코드 반복 줄이기를 시도했는데 효율성 문제로 실패했습니다.
짝지어 제거하기도 효율성 문제로 3시간 가까이 삽질하다가 질문하기에서 'stack'을 사용한다는 힌트를 보고 나서야 쉽게 풀었습니다....
반나절 이상 붙들었더니 너무 힘드네요 ㅠㅠ
--- 
커밋 실수로 저번주 코드가 포함 되어 있습니다.
앞에 5개 코드는 skip 해주시면 됩니다!

220302 ljh

---

Test
Ywy/JAVA/src/level2/MenuRenewal.java
Ywy/JAVA/src/level2/ParenthesesConversion.java
Ywy/JAVA/src/level2/test/AllTests.java
Ywy/JAVA/src/level2/test/MarchWeekOf2.java
Ywy/JAVA/src/level2/test/cases/MenuRenewalTest.java
Ywy/JAVA/src/level2/test/cases/ParenthesesConversionTest.java
Ywy/JavaScript/level2/MenuRenewal.js
Ywy/JavaScript/level2/ParenthesesConversion.js
Ywy/JavaScript/level2/test/MenuRenewal.test.js
Ywy/JavaScript/level2/test/ParenthesesConversion.test.js

**통과 현황**
**풀이**
1. orders 배열 인자를 순회하면서 각각의 order의 menu를 맵에 저장하면서 카운팅한다.
2. orders 배열 인자를 순회하면서 각각의 order의 menu들을 조합하기 전 맵에서 해당 menu들이 몇번 카운팅 됐는지 확인하고 두 개 이상이면 menu 조합에 포함한다.
3. menu들을 조합하면서 새로운 맵에 조합한 메뉴들을 저장하면서 카운팅한다. (저장할 때 사전순으로 정렬한다.)
4. 조합한 메뉴들의 정보가 있는 맵을 순회하면서 카운팅한 횟수가 2이상이며 많이 조합된 메뉴들을 새로운 맵에 저장한다.
5. 가장 많이 조합된 메뉴들의 정보가 있는 맵을 순회하면서 결과를 저장하는 배열에 저장한다.
6. 결과를 저장한 배열의 요소들을 사전순으로 정렬 후 결과로 반환한다.
**리뷰**
계속 못 풀어서 앤디님한테 "재귀는 싫고 반복문으로 짜고 싶어요!!"라며 찡찡댓는데 앤디님이 아이디어와 코드를 주셨다.. ㅎㅎ 그래서 앤디님이 설명해주신 아이디어를 되새기며 코딩을 했다. 2레벨... 나에겐 너무.... ㅠㅠ
***
**통과 현황**
**풀이**
1. p 파라메터에서 u와 v변수의 리터럴을 자를 때가 중요하다.
2. p 파라메터를 char array로 변환 후 순회하면서 **"("** 는 leftCount, **")"** 는 rightCount로 카운팅한다.
7. leftCount와 rightCount가 같다면 *균형잡힌 괄호 문자열* 이다.
8. *균형잡힌 괄호 문자열* 이면 반복문을 끝내고 index변수에 leftCount와 rightCount를 합산하여 대입한다.
9. …

2022-03-09 ywy

---

ljh/level2/거리두기 확인하기/DistancingCheck.java
ljh/level2/거리두기 확인하기/DistancingCheck.js
ljh/level2/뉴스 클러스터링/NewsClustering.java
ljh/level2/뉴스 클러스터링/NewsClustering.js

Ljh (거리두기 확인하기, 뉴스 클러스터링)

---

Andy/src/level2/java/expMax.java
Andy/src/level2/java/ntuple.java
Andy/src/level2/javascript/expMax.js
Andy/src/level2/javascript/ntuple.js

**통과 현황**
**분석**
* Javascript는 eval 함수를 사용하여 간단한게 해결하였습니다.
* Java는 스택을 사용하여 후위계산기를 구현하여 해결하였습니다.
***
**통과 현황**
**분석**
* 주어진 문자열을 각각 분리하고 정렬하여, 이전값과 비교하여 추가된숫자만큼의 값을 추가하도록 하였습니다.

Andy (수식최대화, 튜플)

---

ljh/level2/수식 최대화/Solution.java
ljh/level2/수식 최대화/Solution.js
ljh/level2/튜플/Tuple.java
ljh/level2/튜플/Tuple.js

Ljh (수식 최대화, 튜플)

---

Andy/src/boj/rotateQueue/1021.js
Andy/src/boj/rotateQueue/Main.java

백준 1021 회전하는큐

---

ljh/BAEKJOON/1406_에디터/Editor.java
ljh/BAEKJOON/1406_에디터/Editor.js

**통과 현황**
**리뷰**
java는 양방향 연결 리스트를 활용했습니다.
javascript는 stack을 활용했습니다.
(js의 경우, 백준에 공개되어 있는 다른 사람의 풀이를 참고 했습니다.)

Ljh(백준 1406 에디터)

---

Andy/src/boj/editor/1406.js
Andy/src/boj/editor/Main.java

**통과 현황**
**분석**
* 링크드 리스트를 사용하여, 문자를 중간에 삽입또는 삭제하도록 구현해야한다.
**풀이**
1. Java는 LinkedList가 있어서 해당 클래스를 사용하여 간단하게 구현할수있다.
2. Javascript는 해당 자료형이 없어서 직접 LinkedList를 구현하였습니다.
***

백준, 1406, 에디터

---

ljh/BAEKJOON/1560_비숍/Bishop.java
ljh/BAEKJOON/1560_비숍/Bishop.js

백준 1560 비숍 java/js

---

Andy/src/boj/boj2579/2579.js
Andy/src/boj/boj2579/Main.java

백준, 2579, 계단 오르기

---

Andy/src/boj/1149.js

**분석**
* 계단오르기보다 더 단순한구조, 계단은 아래 두칸까지 체크해야되지만, 이문제는 바로 앞의 집만 체크하면 됨.
***

백준, 1149, RGB거리

---

1149_RGB거리/RGB.js
ljh/BAEKJOON/2579_계단오르기/ClimbStairs.java
ljh/BAEKJOON/2579_계단오르기/ClimbStairs.js

**통과 현황**
===================================================================
**통과 현황**

계단오르기, RGB거리 (javaScript)

---

Andy/src/boj/2302.js
Andy/src/boj/3019.js

**통과 현황**
**풀이**
1. 피보나치수열의 대표적인 문제.
**리뷰**
어려울것같았는데, 생각보다 쉽게 풀었음.
***

백준, 2302, 극장 좌석

---

ljh/BAEKJOON/2302_극장좌석/Theater.js

백준_2302_극장좌석_javascript

---

Andy/src/boj/3019.js

백준, 3019, 테트리스

---

Andy/src/boj/1912.js

백준, 1912, 연속합

---

Andy/src/boj/1334.js
Andy/src/boj/2688.js

백준, 줄어들지 않아

---

Andy/src/boj/15918.js

**통과 현황**
**분석**
* 큰수부터 시작해서 작은수까지 모든 경우의 수를 탐색하여 해결하였습니다.

백준, 15918, 랭퍼든 수열쟁이야!!

---

Andy/src/boj/1325.cpp

**통과 현황**
**분석**
* Javascript로 풀었으나 시간초과가 발생.
* 혹시나 해서 같은 알고리즘으로 C++로 해보니 통과가 되었습니다.

백준, 1325, 효율적인 해킹

---

Andy/src/boj/4963.js

**통과 현황**
재귀호출을 사용하여, 모든 섬을 검색하였습니다.

백준, 4963 섬의개수

---

ljh/BAEKJOON/2644_촌수계산/Solution2.js
ljh/BAEKJOON/2805_나무자르기/Solution.js

촌수계산 / 나무자르기

---

Andy/src/boj/1388.js
Andy/src/boj/2644.js
Andy/src/boj/2805.js
Andy/src/boj/2805_1.js

백준, 2805, 나무 자르기
백준, 2644, 촌수계산
백준, 1388, 바닥 장식
**통과 현황**
***
**통과 현황**
***
**통과 현황**

백준, 2805, 나무 자르기

---

Andy/src/boj/1058.js
Andy/src/boj/1541.js

**통과 현황**
**분석**
* - 부호를 기준으로 각각 그룹으로 나누어서 계산하였습니다.
**통과 현황**

백준, 1541_잃어버린 괄호, 1058_친구

---

Andy/src/boj/1874.js
Andy/src/boj/2108.js

백준, 2108, 통계학 1874, 스택 수열
